<?php

namespace SarahBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
    public function existCompteur($compteur){
        return $this->createQueryBuilder('a')
            ->where('a.compteur = :compteur')
            ->setParameter('compteur',$compteur)
            ->getQuery()
            ->getSingleResult();
    }
}
